# PHP
# Test and package your PHP application.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  phpVersion: 7.2

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'

- script: cp .env.example .env
  displayName: 'Generate .env file from the provided .env.Example'

- script: php artisan key:generate
  displayName: 'Generate 32 bit encryption key for the app'

- script: ./vendor/bin/phpunit --log-junit ./reports/junit.xml --coverage-html ./reports --coverage-xml ./reports
  displayName: 'Run tests with composer using phpunit'

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFiles: './reports/junit.xml'
    alwaysRun: 'true'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'jaCoCo' # Options: cobertura, jaCoCo
    summaryFileLocation: './reports/index.xml'
    reportDirectory: './reports/'
    #additionalCodeCoverageFiles: # Optional

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'Reports'
    targetPath: './reports/'
    alwaysRun: 'true'